%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GeoFoundation
%
% Example:
%   Example_PlotSoilProfile
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear;
clc;
close all;

run('../scripts/SetupGeoFoundation.m')

%% Create Soil Layers

layer1 = gf_CreateLayer(...
    "Clayey Gravel",...
    0,...
    4,...
    20,...
    40000,...
    0.30);

layer2 = gf_CreateLayer(...
    "Stiff Clay",...
    4,...
    14,...
    19,...
    25000,...
    0.35);

layer3 = gf_CreateLayer(...
    "Hard Clay",...
    14,...
    26,...
    20,...
    60000,...
    0.30);

%% Create Profile

profile = gf_CreateProfile(layer1,layer2,layer3);

%% Validate

gf_ValidateProfile(profile);

%% Plot

gf_PlotSoilProfile(profile);
